// Auto-generated bytecode sizes
#include <stddef.h>
const size_t luaJIT_BC_lexer_size = 0x0000000000000c5f;
const size_t luaJIT_BC_parser_size = 0x0000000000001bc9;
const size_t luaJIT_BC_codegen_size = 0x00000000000014f5;
const size_t luaJIT_BC_main_size = 0x000000000000078b;
