CC = $(shell which cc)
LUAJIT = $(shell which luajit)
AR = $(shell which ar)
OUT = cz

# Use pkg-config to get LuaJIT flags if available, otherwise use defaults
LUAJIT_CFLAGS := $(shell pkg-config --cflags luajit 2>/dev/null || echo "-I/usr/include/luajit-2.1")
LUAJIT_LIBS := $(shell pkg-config --libs luajit 2>/dev/null || echo "-lluajit-5.1")

# Check if static linking is requested
ifdef STATIC
    # Try to find static library
    LUAJIT_STATIC := $(shell pkg-config --variable=libdir luajit 2>/dev/null)/libluajit-5.1.a
    ifneq ($(wildcard $(LUAJIT_STATIC)),)
        LUAJIT_LIBS := $(LUAJIT_STATIC)
        LDFLAGS_EXTRA := -static
    else
        # Fallback to default static library path
        LUAJIT_STATIC := /usr/lib/x86_64-linux-gnu/libluajit-5.1.a
        ifneq ($(wildcard $(LUAJIT_STATIC)),)
            LUAJIT_LIBS := $(LUAJIT_STATIC)
            LDFLAGS_EXTRA := -static
        else
            $(warning Static LuaJIT library not found, falling back to dynamic linking)
        endif
    endif
endif

CFLAGS = $(LUAJIT_CFLAGS) -O2
LDFLAGS = -L. -Wl,--whole-archive -lczar -Wl,--no-whole-archive -Wl,-E $(LUAJIT_LIBS) -lm -ldl $(LDFLAGS_EXTRA) -s

# Lua source files
LUA_SOURCES = main.lua lexer.lua parser.lua codegen.lua
LUA_OBJECTS = main.o lexer.o parser.o codegen.o
LUA_LIBRARY = libczar.a

.PHONY: all build clean test syntax-check install help

# Default target: build the cz binary from Lua bytecode
all: build test

# Build the cz binary from Lua bytecode
build: $(OUT)
	@echo "Build complete: $(OUT)"

test:
	@./check.sh tests/*.cz

# Helper
help:
	@echo "Czar Compiler Build System"
	@echo "Commands:"
	@echo "  make build         - Build the cz compiler"
	@echo "  make test          - Run full test suite with exit code validation"
	@echo "  make syntax-check  - Quick syntax check of all test files"
	@echo "  make clean         - Clean build artifacts"
	@echo "  make install       - Install cz to /usr/local/bin"

# Link the C main file with the Lua library to create the binary
$(OUT): main.c main.h $(LUA_LIBRARY)
	$(CC) $(CFLAGS) -o $@ main.c $(LDFLAGS)

# Compile Lua files to object files and create static library
$(LUA_LIBRARY): $(LUA_OBJECTS)
	$(AR) rcs $@ $^

# Compile individual Lua files to bytecode object files
lexer.o: lexer.lua
	$(LUAJIT) -b $< $@

parser.o: parser.lua
	$(LUAJIT) -b $< $@

codegen.o: codegen.lua
	$(LUAJIT) -b $< $@

main.o: main.lua
	$(LUAJIT) -b $< $@

# Generate sizes file from object files
main.h: $(LUA_OBJECTS)
	@echo "// Auto-generated by Makefile" > $@
	@echo "#include <stddef.h>" >> $@
	@for obj in $(LUA_OBJECTS); do \
		name=$$(basename $$obj .o); \
		size=$$(nm -S $$obj | grep luaJIT_BC | awk '{print "0x" $$2}'); \
		echo "const size_t luaJIT_BC_$${name}_size = $$size;" >> $@; \
	done

# Quick syntax check using cz test command
syntax-check: build
	@./cz test tests/

# Clean build artifacts
clean:
	@rm -vf ./$(OUT) ./a.out ./*.o ./*.a ./$(OUT) ./$(LUA_LIBRARY) ./main.h
	@find ./tests -type f -name '*.c' -print | xargs rm -vf
	@find ./tests -type f -executable -print | xargs rm -vf

# Install the cz compiler (requires root/sudo for system-wide install)
install: build
	@echo "Installing $(OUT) to /usr/local/bin/$(OUT)"
	@echo "You may need to run this with sudo"
	install -m 755 ./$(OUT) /usr/local/bin/cz
	@echo "Installation complete. You can now use '$(OUT)' from anywhere."
