CC = $(shell which cc)
LUAJIT = $(shell which luajit)
AR = $(shell which ar)
OUT = cz

# Use pkg-config to get LuaJIT flags if available, otherwise use defaults
LUAJIT_CFLAGS := $(shell pkg-config --cflags luajit 2>/dev/null || echo "-I/usr/include/luajit-2.1")
LUAJIT_LIBS := $(shell pkg-config --libs luajit 2>/dev/null || echo "-lluajit-5.1")

# Check if static linking is requested
ifdef STATIC
    # Try to find static library
    LUAJIT_STATIC := $(shell pkg-config --variable=libdir luajit 2>/dev/null)/libluajit-5.1.a
    ifneq ($(wildcard $(LUAJIT_STATIC)),)
        LUAJIT_LIBS := $(LUAJIT_STATIC)
        LDFLAGS_EXTRA := -static
    else
        # Fallback to default static library path
        LUAJIT_STATIC := /usr/lib/x86_64-linux-gnu/libluajit-5.1.a
        ifneq ($(wildcard $(LUAJIT_STATIC)),)
            LUAJIT_LIBS := $(LUAJIT_STATIC)
            LDFLAGS_EXTRA := -static
        else
            $(warning Static LuaJIT library not found, falling back to dynamic linking)
        endif
    endif
endif

CFLAGS = $(LUAJIT_CFLAGS) -O2
LDFLAGS = -L. -Wl,--whole-archive -lczar -Wl,--no-whole-archive -Wl,-E $(LUAJIT_LIBS) -lm -ldl $(LDFLAGS_EXTRA) -s

# Lua source files
LUA_SOURCES = main.lua lexer.lua parser.lua codegen.lua
LUA_OBJECTS = main.o lexer.o parser.o codegen.o
LUA_LIBRARY = libczar.a

.PHONY: all build clean test install help

# Default target: build and run tests
all: build test

# Helper
help:
	@echo "Czar Compiler Build System"
	@echo "make [STATIC=1] build"
	@make -qp | grep -oP '^[a-z]+:( [a-z]+)?' | cut -d':' -f1 | sort

# Build the cz binary from Lua bytecode
build: $(OUT)
	@echo "Build complete: $(OUT)"

# Link the C main file with the Lua library to create the binary
$(OUT): main.c main.h $(LUA_LIBRARY)
	$(CC) $(CFLAGS) -o $@ main.c $(LDFLAGS)

# Compile Lua files to object files and create static library
$(LUA_LIBRARY): $(LUA_OBJECTS)
	$(AR) rcs $@ $^

# Compile individual Lua files to bytecode object files
lexer.o: lexer.lua
	$(LUAJIT) -b $< $@

parser.o: parser.lua
	$(LUAJIT) -b $< $@

codegen.o: codegen.lua
	$(LUAJIT) -b $< $@

main.o: main.lua
	$(LUAJIT) -b $< $@

# Generate sizes file from object files
main.h: $(LUA_OBJECTS)
	@echo "// Auto-generated by Makefile" > $@
	@echo "#include <stddef.h>" >> $@
	@for obj in $(LUA_OBJECTS); do \
		name=$$(basename $$obj .o); \
		size=$$(nm -S $$obj | grep luaJIT_BC | awk '{print "0x" $$2}'); \
		echo "const size_t luaJIT_BC_$${name}_size = $$size;" >> $@; \
	done

# Find all test .cz files
TEST_FILES = $(wildcard tests/*.cz)
EXPECTED_RESULTS = \
	types:42 \
	bindings:30 \
	structs:15 \
	pointers:30 \
	functions:19 \
	arithmetic:53 \
	comparison:1 \
	if_else:50 \
	while:55 \
	comments:60 \
	no_semicolons:15 \
	logical_operators:1 \
	null_pointer:42 \
	field_assignment:20

# Run the test suite
test: build
	@echo "Running all tests..."
	@passed=0; failed=0; \
	for test in $(TEST_FILES); do \
		name=$$(basename $$test .cz); \
		echo -n "Testing $$name..."; \
		./cz $$test -o tests/$$name > /dev/null 2>&1; \
		compile_status=$$?; \
		if [ $$compile_status -ne 0 ] || [ ! -f tests/$$name ]; then \
			echo " FAIL: Compilation failed"; \
			failed=$$((failed + 1)); \
			continue; \
		fi; \
		tests/$$name; \
		exit_code=$$?; \
		expected=$$(echo "$(EXPECTED_RESULTS)" | tr ' ' '\n' | grep "^$$name:" | cut -d: -f2); \
		if [ -n "$$expected" ]; then \
			if [ $$exit_code -eq $$expected ]; then \
				echo " PASS (exit code: $$exit_code)"; \
				passed=$$((passed + 1)); \
			else \
				echo " FAIL: Expected exit code $$expected, got $$exit_code"; \
				failed=$$((failed + 1)); \
			fi; \
		else \
			echo " PASS (exit code: $$exit_code, no expected value)"; \
			passed=$$((passed + 1)); \
		fi; \
	done; \
	echo "Results: $$passed passed, $$failed failed"; \
	if [ $$failed -gt 0 ]; then exit 1; fi

# Clean build artifacts
clean:
	rm -f ./$(OUT) ./a.out ./*.o ./*.a ./$(OUT) ./$(LUA_LIBRARY) ./main.h
	find ./tests/*.c -delete
	find ./tests/* -executable -delete

# Install the cz compiler (requires root/sudo for system-wide install)
install: build
	@echo "Installing $(OUT) to /usr/local/bin/$(OUT)"
	@echo "You may need to run this with sudo"
	install -m 755 ./$(OUT) /usr/local/bin/cz
	@echo "Installation complete. You can now use '$(OUT)' from anywhere."
