name: Setup
description: LuaJIT
runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config luajit libluajit-5.1-dev
        luajit -v || true
